### ISSUE TITLE
`clean-repo-tabs`: Cannot read property 'removeAttribute' of undefined

### ISSUE THREAD

**Issue by yakov116** [refined-github/refined-github#4660]
URL: https://github.com/sindresorhus/refined-github/issues/4653?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDIyNzUyNTk0Mzc6MTY4NzI3OTM%3D#issuecomment-897596871

To trigger, open any norification.

```
TypeError: Cannot read property 'removeAttribute' of undefined
  at onlyShowInDropdown (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:10570:12)
  at init (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:4894:76)
  at async runFeature (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:9159:11)
  at async setupPageLoad (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:9177:5)
```
	

I cannot figure out why? It looks like sometimes 
https://github.com/sindresorhus/refined-github/blob/f56ac118ade1b34513a46fb0f6f699e53883ada1/source/features/more-dropdown-links.tsx#L29

Does not exist, but its not consistent. 🤷‍♂️

**Comment by yakov116** [comment]
Go from any notification

**Comment by yakov116** [comment]
Not happening anymore
