### ISSUE TITLE
`release-download-count`: GraphQL:Parse error on ":" (COLON) at [4, 23]

### ISSUE THREAD

**Issue by EverlastingBugstopper** [refined-github/refined-github#5713]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/apollographql/federation-rs/releases/tag/supergraph%40v2.0.5

### Extension version

22.5.22

### Browser(s) used

Microsoft Edge

### Description

```
Error: GraphQL:
Parse error on ":" (COLON) at [4, 23]
    at mem.cacheKey (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:4069:60)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:8319:32
    at async init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:8318:24)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3913:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3921:34)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3946:29
```

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by yakov116** [comment]
**Assuming** because the release has an "@" in it and its not escaped properly, I can try to check later.
