### ISSUE TITLE
`toggle-files-button`: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by bertho-zero** [refined-github/refined-github#5864]
### Description

```
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at observeElement (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:6796:23)
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:6898:28)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3955:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3961:34)
```

### How to replicate the issue

Click on a folder in a repo

### Extension version

22.7.20

### Browser(s) used

Brave

**Comment by kidonng** [comment]
`repo-age` is also failing:

```
❌ repo-age
refined-github.js:3897 📕 22.7.20 → TypeError: Cannot read properties of undefined (reading 'append')
    at init (refined-github.js:9163:70)
    at async runFeature (refined-github.js:3955:20)
    at async setupPageLoad (refined-github.js:3961:34)
```

I think there's some race condition?

**Comment by fregante** [comment]
Both work, it’s just an ajax issue. Closing since it’s tracked in https://github.com/refined-github/refined-github/issues/5835
