### ISSUE TITLE
`releases-tab`: Cannot read properties of undefined (reading 'append')

### ISSUE THREAD

**Issue by jkroepke** [refined-github/refined-github#5876]
### Description

```
TypeError: Cannot read properties of undefined (reading 'append')
    at appendBefore (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:5711:60)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:5765:54
    at async init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:5744:55)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3955:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3961:34)
```

### How to replicate the issue

Error appears, if developers tools are enabled and a mobile device is selected. 

### Extension version

22.7.20

### Browser(s) used

Chrome 103

**Comment by fregante** [comment]
- Tracked in https://github.com/refined-github/refined-github/issues/5895
