### ISSUE TITLE
`set-default-repositories-type-to-sources`: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#5940]
### Description

New GH Projects pages trigger this error:

```
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:7536:13
    at new Promise (<anonymous>)
    at oneMutation (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:7532:14)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:7587:51
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:7585:9
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3851:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3857:34)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3882:29
```

### How to replicate the issue

Just open https://github.com/users/janpio/projects/3/views/1 and observe Console

### Extension version

22.8.23

### Browser(s) used

Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by fregante** [comment]
Likely because there's an extra dropdown on the page
<img width="314" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/188281567-5e8d9ae6-9d52-4c0f-b23d-e02d157fa6ce.png">
