### ISSUE TITLE
`list-prs-for-file`: Cannot read properties of undefined (reading 'getAttribute')

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6299]
### Description

```
 0.0.0 → TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at getCurrentPath (refined-github.js:9747:18)
    at async Promise.all (index 0)
    at async init (refined-github.js:9750:29)
    at async runFeature (refined-github.js:3797:16)
    at async setupPageLoad (refined-github.js:3809:5)
```

### How to replicate the issue + URL

1. https://github.com/refined-github/yolo/blob/main/broken-features.csv

### Extension version

23.2.1

### Browser(s) used

Chrome

**Comment by miketheman** [comment]
Ran into this today, version 23.3.2

**Comment by AdamRaichu** [comment]
Still in `23.4.10`.
