### ISSUE TITLE
`clean-header-search-field`: Cannot set properties of undefined (setting 'textContent')

### ISSUE THREAD

**Issue by derN3rd** [refined-github/refined-github#6439]
### Description

Just when loading the URL, the dev console shows me this error message. Seems like Github has updated/changed some names

```
TypeError: Cannot set properties of undefined (setting 'textContent')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:10345:100)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3554:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3560:34)
```

### How to replicate the issue + URL

https://github.com/Ryujinx/Ryujinx/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

### Extension version

23.3.20

### Browser(s) used

Google Chrome: Version 111.0.5563.110 (Official Build) (arm64)

**Comment by fregante** [comment]
Thanks for the report! It will be fixed shortly
