### ISSUE TITLE
`clean-repo-sidebar`: Cannot read properties of undefined (reading 'parentElement')

### ISSUE THREAD

**Issue by maicol07** [refined-github/refined-github#6569]
### Description

```
TypeError: Cannot read properties of undefined (reading 'parentElement')
    at moveReportLink (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:5143:90)
    at async Promise.all (index 4)
    at async init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:5150:75)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3718:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3724:34)
```

### How to replicate the issue + URL

https://github.com/perfect-things/perfect-home?search=1

### Extension version

23.4.15

### Browser(s) used

Edge dev

**Comment by fregante** [comment]
Thank you for the report. This is a consequence of:

- https://github.com/refined-github/refined-github/pull/6500

Either they haven't enabled it for you or they already changed it. 

Cc @kidonng what do you suggest we do? Probably GHE won't ever have the link

**Comment by fregante** [comment]
Oh, no. I see what's happening. This page is incorrectly detected as `isRepoHome`, but it looks completely different: https://refined-github.github.io/github-url-detection/?url=%2Fperfect-things%2Fperfect-home%3Fsearch%3D1

It should be fixed in https://github.com/refined-github/github-url-detection

**Comment by fregante** [comment]
Closing in favor of https://github.com/refined-github/github-url-detection/issues/173
