### ISSUE TITLE
`ci-link`: Cannot read properties of undefined (reading 'parentElement')

### ISSUE THREAD

**Issue by maicol07** [refined-github/refined-github#6570]
### Description

```
TypeError: Cannot read properties of undefined (reading 'parentElement')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:6375:65)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3718:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3724:34)
```

### How to replicate the issue + URL

https://github.com/perfect-things/perfect-home?search=1

### Extension version

23.4.15

### Browser(s) used

Edge dev

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/6454
