### ISSUE TITLE
`latest-tag-button`: Cannot read properties of undefined (reading 'closest')

### ISSUE THREAD

**Issue by maicol07** [refined-github/refined-github#6571]
### Description

```
TypeError: Cannot read properties of undefined (reading 'closest')
    at addAfterBranchSelector (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:6197:50)
    at async init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:6313:9)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3718:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/refined-github.js:3724:34)
```

### How to replicate the issue + URL

https://github.com/perfect-things/perfect-home?search=1

### Extension version

23.4.15

### Browser(s) used

Edge dev

**Comment by fregante** [comment]
Thank you for the report. The feature will be rewritten in https://github.com/refined-github/refined-github/issues/6250
