### ISSUE TITLE
`one-click-review-submission` feature broken

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#6618]
### Description

Oops

<img width="664" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/236553449-ce9a4284-e636-44f4-8e70-02debdea862f.png">

```
TypeError: Cannot read properties of undefined (reading 'append')
    at addButtons (chrome-extension://jfnbjdajagmjideggedlljgaddlmffhd/refined-github.js:10503:15)
    at init (chrome-extension://jfnbjdajagmjideggedlljgaddlmffhd/refined-github.js:10568:3)
    at runFeature (chrome-extension://jfnbjdajagmjideggedlljgaddlmffhd/refined-github.js:3793:22)
    at setupPageLoad (chrome-extension://jfnbjdajagmjideggedlljgaddlmffhd/refined-github.js:3805:11)
    at chrome-extension://jfnbjdajagmjideggedlljgaddlmffhd/refined-github.js:3857:15
```

Probably it's what was being requested in https://github.com/refined-github/refined-github/issues/6048#issuecomment-1536531740

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/pull/6617/files

### Extension version

23.4.26

### Browser(s) used

Chrome, Safari

**Comment by matthewhively** [comment]
Just encountered this myself.

Its funny, I've gotten so used to github refined I don't even remember what the github UI looks like without the changes.
