### ISSUE TITLE
`restore-file`: GraphQL:Field 'compare' doesn't exist on type 'Ref'

### ISSUE THREAD

**Issue by Geczy** [refined-github/refined-github#6737]
### Description

```
Error: GraphQL:
Field 'compare' doesn't exist on type 'Ref'
    at v4uncached (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4454:60)
    at async getPrInfo (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:8493:28)
    at async getHeadReference (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:9278:52)
    at async Promise.all (index 0)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:9294:41
    at async showToast (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:6296:40)
    at async HTMLHtmlElement.handleClick (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:9293:9)
```

### How to replicate the issue + URL

https://github.com/dotabod/backend/pull/269/files

tried to discard changes button

note that i'm doing this in a private github enterprise 3.7.6 server

<img width="385" alt="CleanShot 2023-06-12 at 13 53 05@2x" src="https://github.com/refined-github/refined-github/assets/1036968/86a18a3a-f4eb-443b-ad07-d696c12a2b52">

### Extension version

23.6.2

### Browser(s) used

chrome

**Comment by fregante** [comment]
Thanks for the report. It looks like the API was added in GHE 3.8, so you’d have to wait until your Enterprise installation is updated  https://docs.github.com/en/enterprise-server@3.8/graphql/reference/objects#ref
