### ISSUE TITLE
`release-download-count` is broken

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#7125]
### Description

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at addCounts (refined-github.js:8917:146)
    at refined-github.js:4650:9
```

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/releases

### Extension version

23.11.23

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
Funny as this is caused by our very own `visit-tag`:

https://github.com/refined-github/refined-github/blob/461eb5cf467feaf240dcd87d78873c579245473f/source/features/visit-tag.tsx#L34-L37

BTW, the replacement does not work if I visit a release directly:

![image](https://github.com/refined-github/refined-github/assets/44045911/d23278df-9115-47f8-bc67-de4c0035c484)
