### ISSUE TITLE
`restore-file`: GraphQL:A path was requested for deletion which does not exist as of commit oid `4ec33cf263e0a086bffb40f15b39a7de3c5044b8`

### ISSUE THREAD

**Issue by govindrai** [refined-github/refined-github#7312]
### Description

```
Error: GraphQL:
A path was requested for deletion which does not exist as of commit oid `4ec33cf263e0a086bffb40f15b39a7de3c5044b8`
    at v4uncached (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4392:60)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:8471:11
    at async showToast (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:5378:40)
    at async HTMLHtmlElement.handleClick (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:8454:9)
```

### How to replicate the issue + URL

I had a large PR (270 files). I discarded changes on two files. It worked beautifully. Upon restoring my third file, I started getting this error. A this point I had to do the discards manually via git. 

### Extension version

24.3.20

### Browser(s) used

Chrome Version 123.0.6312.59 (Official Build) (arm64)

**Comment by fregante** [comment]
I think this happens when you delete multiple files in a row. Refreshing the page should work

**Comment by govindrai** [comment]
I tried that multiple times, Even tried to clear cache/exit browser. It would always give the same error.

**Comment by fregante** [comment]
This is likely a caching issue, all of our API calls are cached until the next page refresh. If that doesn't do it, it's likely that GitHub is also caching the request.

https://github.com/refined-github/refined-github/blob/c8902e57a144e830f96dec04db42539c9d5f7655/source/features/restore-file.tsx#L17

We should either:

- create a `v3uncached` method like we do for v4: https://github.com/refined-github/refined-github/blob/c8902e57a144e830f96dec04db42539c9d5f7655/source/github-helpers/api.ts
- add a cache buster

I think the latter is easier and safer, if the caching issue is actually on GitHub's side

**Comment by fregante** [comment]
Can still repro on the latest version

**Comment by fregante** [comment]
Closing because it's hard to replicate. It only happens when I try to delete many files very fast, and even then it's rare.
