### ISSUE TITLE
`more-conversation-filters`: Cannot read properties of undefined (reading 'cloneNode')

### ISSUE THREAD

**Issue by klippx** [refined-github/refined-github#7453]
### Description

```
TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:6109:112)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4057:28
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4053:64
    at Array.map (<anonymous>)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4053:45
    at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4054:10)
    at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4069:43)
```

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

### Extension version

24.6.13.1731

### Browser(s) used

Arc 1.46

**Comment by fregante** [comment]
Can't repro, is it related to #7447? I'll release a new version anyway, let me know if you still see the issue there
