### ISSUE TITLE
`tags-on-commits-list`: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by Chriscbr** [refined-github/refined-github#7459]
### Description

```
TypeError: Cannot read properties of undefined (reading 'pathname')
    at getCommitHash (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:7129:35)
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:8406:132)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4225:28
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4221:64
    at Array.map (<anonymous>)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4221:45
    at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4222:10)
    at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4237:43)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4262:11
```

### How to replicate the issue + URL

https://github.com/winglang/winglibs/commits/main/

### Extension version

24.6.9

### Browser(s) used

Arc version 1.46.0 (50665) - Chromium Engine Version 125.0.6422.142

**Comment by fregante** [comment]
Version 24.6.14 will be available soon for Chrome, within 24 hours. Can you double check when you see it?

**Comment by vitoyucepi** [comment]
Hi, it seems the same problem exists in 24.6.14.
I have been using the version for local testing from the github release artifacts.
I also get the problem, which looks similar to this, with firefox 127.0 on a clean profile with version 24.6.14.
