### ISSUE TITLE
`tags-on-commits-list`: Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by eranb-di** [refined-github/refined-github#7515]
### Description

```
TypeError: Cannot read properties of undefined (reading 'pathname')
    at getCommitHash (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:6936:35)
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:8223:132)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4065:28
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4061:64
    at Array.map (<anonymous>)
    at chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4061:45
    at runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4062:10)
    at setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/refined-github.js:4077:43)
```

<details>
<summary>Details</summary>

</details>

### How to replicate the issue + URL

https://github.com/refined-github/refined-github/commits/main/

### Extension version

24.6.21

### Browser(s) used

Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by fregante** [comment]
Thanks for the report! Fixed by https://github.com/refined-github/refined-github/pull/7495, not yet released
