### ISSUE TITLE
`tags-on-commits-list`: Expected element not found because the base is specified but null

### ISSUE THREAD

**Issue by josephharrington** [refined-github/refined-github#7954]
### Description

```
ElementNotFoundError: Expected element not found because the base is specified but null
    at expectElement (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/npm/select-dom.js:15:15)
    at getCommitHash (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/mark-merge-commits-in-list.js:40:15)
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/tags-on-commits-list.js:90:27)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/feature-manager.js:119:19
    at async Promise.all (index 0)
    at async asyncForEach (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/helpers/async-for-each.js:6:2)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/feature-manager.js:118:3)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/feature-manager.js:133:3)
```

### How to replicate the issue + URL

Public GitHub URL: https://github.com/microsoft/vscode/commits/release/1.25/
Note issue does not occur on this public GitHub though -- tags will show correctly at this URL. The issue seems to be specific to GitHub Enterprise. I observed this issue on GitHub Enterprise Server 3.13.4.

The problem is that the tags are not being shown next to the commits. From debugging it appears to be a difference between GH and GHE in how the page is loaded. I set a breakpoint in [tags-on-commits-list.js](https://github.com/refined-github/refined-github/blob/main/source/features/tags-on-commits-list.tsx#L91-L93) and I see that `commitsOnPage` is an empty list because the commit list has actually not yet been rendered on the page. This seems to cause the next line to throw an error.

<img width="891" alt="Screenshot 2024-10-24 at 12 38 45" src="https://github.com/user-attachments/assets/0454277a-33c5-4504-b46e-6d0d718b9c0a">

### Extension version

24.10.14

### Browser(s) used

Chrome

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Parent issue:

- #7808 


cc @kovsu since you fixed this last summer

**Comment by kovsu** [comment]
@fregante I don't have GitHub Enterprise, it's hard for me to fix. 🥲

**Comment by fregante** [comment]
@josephharrington can you paste the HTML from a single row? You can censor sensitive information.

This is likely a simple issue but at a minimum we'd need to know what class needs to be used. Would you be able to send a PR?

**Comment by josephharrington** [comment]
I think the selector is correct; the problem is more that there are no rows at all when that plugin's `init` function runs. After the page is fully rendered, then I can run the same `$$('[data-testid="commit-row-item"]')` function in the console and it successfully gets a list of commits from the page.

Is there a way to change the tags-on-commits-list plugin so that it executes its code later? I'm not sure what the plugin lifecycle hooks are.

**Comment by fregante** [comment]
Oh I see, so this is the fix: https://github.com/refined-github/refined-github/issues/7000#issuecomment-2285952033

It should probably also use batchedFunction(). Usage examples of observer + batchedFunction can be found on the codebase. Caching should probably also be applied per commit (difficult) or just removed.

**Comment by kovsu** [comment]
@fregante Should we use `observe` to do it?

**Comment by fregante** [comment]
Observer + batchedFunction
