### ISSUE TITLE
`bugs-tab`: Expected element not found: .Counter

### ISSUE THREAD

**Issue by gabriel-vanca** [refined-github/refined-github#8158]
### Description

See issue description at: https://github.com/matthizou/github-show-avatars/issues/6#issuecomment-2544227501

```
ElementNotFoundError: Expected element not found: .Counter
    at expectElement (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/npm/select-dom.js:21:11)
    at addBugsTab (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/bugs-tab.js:92:22)
    at async init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/bugs-tab.js:158:3)
    at async chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/feature-manager.js:157:20
    at async Promise.all (index 0)
    at async asyncForEach (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/helpers/async-for-each.js:6:2)
```

### How to replicate the issue + URL

https://github.com/facebook/react/pulls?page=5&q=sort%3Aupdated-desc+is%3Apr+is%3Aopen

### Extension version

24.12.9

### Browser(s) used

Edge

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Thanks for the report! Does it happen all the time? The feature works correctly for me

**Comment by gabriel-vanca** [comment]
It seems to be about 50% of the time working, 50% not working when the feature is enabled and the github-show-avatars extension is also enabled.

**Comment by fregante** [comment]
The feature is broken and unlikely to return
