### ISSUE TITLE
`previous-version`: GraphQL:Something went wrong while executing your query. Please include `CC6E:3A0E74:63D1D1:C7911C:6771F871` when reporting this issue.

### ISSUE THREAD

**Issue by injust** [refined-github/refined-github#8184]
### Description

```
Error: GraphQL:
Something went wrong while executing your query. Please include `CC6E:3A0E74:63D1D1:C7911C:6771F871` when reporting this issue.
    at Object.v4uncached (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/github-helpers/api.js:224:9)
    at async getPreviousCommitForFile (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/previous-version.js:15:21)
    at async getPreviousFileUrl (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/previous-version.js:27:25)
    at async add (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/features/previous-version.js:55:14)
```

### How to replicate the issue + URL

https://github.com/typescript-eslint/typescript-eslint/blob/86409083167bee4ba1ad3ebba22785b3a4a262ee/packages%2Feslint-plugin%2Fdocs%2Frules%2Fstrict-boolean-expressions.mdx

### Extension version

24.12.20

### Browser(s) used

Chrome 131

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Likely related to GitHubURL:

- https://github.com/refined-github/refined-github/issues/8185
- https://github.com/refined-github/refined-github/issues/8180

I'm seeing this:

```json
{
        "filePath": "",
        "resource": "/typescript-eslint/typescript-eslint/commit/86409083167bee4ba1ad3ebba22785b3a4a262ee/packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx"
}
```

which is incorrect, the `filePath` should be `packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx`

Instructions: https://github.com/refined-github/refined-github/pull/8299#discussion_r1967107754

cc @kovsu
